// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bujahanmrijvydnqlpbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1amFoYW5tcmlqdnlkbnFscGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Mjk3ODQsImV4cCI6MjA2OTQwNTc4NH0.aoVZCLbih6AY8LhKcrezT9-1yHKKOXIs2y-IVYPalqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});